_GREET_PROMPT = """너는 매일 아침 새로운 게시된 사업 공고문을 수집하여 이메일을 보내고 있어.
예의 있는 말투로 다음 내용을 포함한 짧은 코멘트를 작성해.
- K-Bot 이름을 언급한 자기 소개 한 문장
- AI경영분석에서 제작된 AI기반 자동화 수집 프로그램으로 수집됨.
- 오늘은 <span class="blue">{new_articles_num}개</span> 새로운 공고가 수집됨.
- 하루를 응원하는 한 줄 코멘트.
* 줄바꿈을 적절히 사용하세요.
"""

WEBSITES = {
    "기업마당": {
        "url": "https://www.bizinfo.go.kr/web/lay1/bbs/S1T122C128/AS/74/list.do;jsessionid=07lypKYR2dAy7shyD9PvsDLETgVH3NjJ544WtiQIHszTTGPUnUgaGOcJx9aX491F.ims_bizwas2_servlet_engine1",
        "css_articles": "#articleSearchForm > div.support_project > div.table_Type_1 > table > tbody > tr",
        "init_article_idx": 0,
        "css_title": "td.txt_l > a",
        "css_date": "td:nth-child(7)",
        "init_page_idx": 1,
        "css_pages": "#container > div.sub_cont > div.page_wrap > a",
        "inner_href": {
            "css_href": "td.txt_l > a",
            "url_src": """f"https://www.bizinfo.go.kr/web/lay1/bbs/S1T122C128/AS/74/{btn_href.get_attribute("href")}" """,
        },
    },
    "과학기술정보통신부": {
        "url": "https://www.msit.go.kr/bbs/list.do?sCode=user&mPid=224&mId=129",
        "css_articles": "#result > div.board_list > div",
        "init_article_idx": 0,
        "css_title": "div.txt > p",
        "css_date": "div.date",
        "init_page_idx": -1,
        "css_pages": "#result > div.board_paging > span.num > a",
        "inner_href": {
            "css_href": "a",
            "url_src": '''f"https://www.msit.go.kr/bbs/view.do?sCode=user&mId=129&mPid=224&pageIndex={page}&bbsSeqNo=100&nttSeqNo={btn_href.get_attribute("onclick").split('(')[1][:-2]}&searchOpt=ALL&searchTxt="''',
        },
    },
    "국가기술표준원": {
        "url": "https://www.kats.go.kr/content.do?cmsid=239",
        "css_articles": "body > div.sub_content > ul > li > ul > li.sub_right > div.subpage_con > table > tbody > tr",
        "init_article_idx": 0,
        "css_date": "td:nth-child(3)",
        "css_title": "td.tbleft > a",
        "init_page_idx": 2,
        "css_pages": "body > div.sub_content > ul > li > ul > li.sub_right > div.subpage_con > div.page_news > a",
        "inner_href": {
            "css_href": "td.tbleft > a",
            "url_src": """f"https://www.kats.go.kr/content.do?{btn_href.get_attribute("href").split("?")[1]}" """,
        },
    },
    "산업통상자원부": {
        "url": "https://www.motie.go.kr/kor/article/ATCLc01b2801b",
        "css_articles": "#cont-body > div.board-tbl.board-list.mo_table > table > tbody > tr",
        "init_article_idx": 0,
        "css_title": "td.ta-l > div > a",
        "css_date": "td:nth-child(4)",
        "init_page_idx": 1,
        "css_pages": "#cont-body > div.board-page > a",
        "inner_href": {
            "css_href": "td.ta-l > div > a",
            "url_src": """f"https://www.motie.go.kr/kor/article/ATCLc01b2801b/{btn_href.get_attribute("onclick").split("'")[1]}/view?mno=&pageIndex={page}&rowPageC=0&schClear=on&startDtD=&endDtD=&searchCondition=1&searchKeyword=" """,
        },
    },
    "서울테크노파크": {
        "url": "https://www.seoultp.or.kr/user/nd19746.do",
        "css_articles": "#contents > table > tbody > tr",
        "init_article_idx": 0,
        "css_date": "td:nth-child(4)",
        "css_title": "td.left > a",
        "init_page_idx": 0,
        "css_pages": "#contents > div.paging > ul > li > a",
        "inner_href": {
            "css_href": "td.left > a",
            "url_src": """f"https://www.seoultp.or.kr/user/nd19746.do?View&pageLS=10&pageST=SUBJECT&pageSV=&page={page}&pageSC=SORT_ORDER&pageSO=DESC&dmlType=&boardNo={btn_href.get_attribute("href").split("'")[5]}&menuCode=www" """,
        },
    },
    "소프트웨어정책연구소": {
        "url": "https://spri.kr/posts?code=notice",
        "css_articles": "#real_contents > div > div > div > div.com_list_box > ul > li",
        "init_article_idx": 0,
        "css_title": "div.title > a",
        "css_date": "div.mark_list_area > div > ul > li:nth-child(1) > span",
        "init_page_idx": 1,
        "css_pages": "#real_contents > div > div > div > div.pagination > a",
        "inner_href": {
            "css_href": "div.title > a",
            "url_src": """f"{btn_href.get_attribute("href")}" """,
        },
    },
    "스마트제조혁신추진단": {
        "url": "https://www.smart-factory.kr/usr/np/nm/ma/noticeMatter",
        "css_articles": "#root > div > div.eu-user-body.sub-body > div.eu-u-body-common > div > div.eu-u-body-content > div.ant-row.mt-20 > div:nth-child(2) > div > div > div > div > div > div > table > tbody > tr",
        "init_article_idx": 1,
        "css_title": "td:nth-child(3) > a",
        "css_date": "td:nth-child(5)",
        "init_page_idx": 0,
        "css_pages": "#root > div > div.eu-user-body.sub-body > div.eu-u-body-common > div > div.eu-u-body-content > div.ant-row.mt-20 > div:nth-child(3) > ul > li > a",
        "inner_href": {
            "css_href": "td:nth-child(3) > a",
            "url_src": """f"https://www.smart-factory.kr/usr/np/nm/ma/noticeMatter" """,
        },
    },
    "이노비즈협회": {
        "url": "https://innobiz.or.kr/IB/news/notice.asp?menuno=1",
        "css_articles": "#wraper > div > section > div > div.tableBox > table > tbody > tr",
        "init_article_idx": 1,
        "css_date": "td:nth-child(4)",
        "css_title": "td:nth-child(3)",
        "init_page_idx": 0,
        "css_pages": "#pageBtn > a",
        "inner_href": {
            "css_href": "td:nth-child(3)",
            "url_src": """f"https://innobiz.or.kr/IB/news/notice_view.asp?idx={btn_href.get_attribute("onclick").split("'")[1]}&menuno=1&bct_s=&ste=&sty=&Page={page}&status_s=" """,
        },
    },
    "이지비즈": {
        "url": "https://www.egbiz.or.kr/prjCategory/a/m/selectPrjCategoryList.do",
        "css_articles": "#listForm > div.bbs_list_wrap > div > table > tbody > tr",
        "init_article_idx": 0,
        "css_title": "td:nth-child(2) > div > a",
        "css_date": "td:nth-child(4)",
        "init_page_idx": -1,
        "css_pages": "#listForm > div.paging > span > a",
        "inner_href": {
            "css_href": "td:nth-child(2) > div > a",
            "url_src": '''f"{btn_href.get_attribute("href")}"''',
        },
    },
    "이지비즈(타기관 지원사업)": {
        "url": "https://www.egbiz.or.kr/prjCategory/a/m/selectPrjCategoryList.do",
        "css_articles": "#listForm1 > div.bbs_list_wrap > div > table > tbody > tr",
        "init_article_idx": 0,
        "css_title": "td:nth-child(2) > div > a",
        "css_date": "td:nth-child(4)",
        "init_page_idx": -1,
        "css_pages": "#listForm1 > div.paging > span > a",
        "inner_href": {
            "css_href": "td:nth-child(2) > div > a",
            "url_src": '''f"{btn_href.get_attribute("href")}"''',
        },
    },
    "이지원": {
        "url": "https://ezone.iitp.kr/common/anno/list",
        "css_articles": "#Content > div.group > div > ul > li",
        "init_article_idx": 0,
        "css_title": "div.bbs_cnt > strong > a",
        "css_date": "div.bbs_cnt > span > strong:nth-child(1) > span",
        "init_page_idx": -1,
        "css_pages": "#Content > nav > ul > li > a",
        "inner_href": {
            "css_href": "div.bbs_cnt > strong > a",
            "url_src": """f\'\'\'https://ezone.iitp.kr{btn_href.get_attribute("onclick").split("'")[1]}\'\'\'""",
        },
    },
    "정보통신기획평가원": {
        "url": "https://www.iitp.kr/kr/1/business/businessApiView.it",
        "css_articles": "#conArea > div.table-responsive > table > tbody > tr",
        "init_article_idx": 0,
        "css_title": "td.no-space.comment-group0 > a",
        "css_date": "td:nth-child(3)",
        "init_page_idx": 2,
        "css_pages": "#conArea > div.row > div > div > ul > li > a",
        "inner_href": {
            "css_href": "td.no-space.comment-group0 > a",
            "url_src": """f"{btn_href.get_attribute("href")}" """,
        },
    },
    "정보통신산업진흥원": {
        "url": "https://www.nipa.kr/home/2-2",
        "css_articles": "#container > div.row.pdl15.pdr15 > div:nth-child(3) > div.bdWrap > table > tbody > tr",
        "init_article_idx": 0,
        "css_title": "td.tl > div > div:nth-child(1) > a",
        "css_date": "td:nth-child(5) > span",
        "init_page_idx": 2,
        "css_pages": "#container > div.row.pdl15.pdr15 > div:nth-child(3) > div:nth-child(10) > div > ul > li > a",
        "inner_href": {
            "css_href": "td.tl > div > div:nth-child(1) > a",
            "url_src": """f"{btn_href.get_attribute("href")}" """,
        },
    },
    "중소기업스마트서비스 지원사업": {
        "url": "https://www.smb-service.kr/pblanc/listUser/1",
        "css_articles": "#body > div.container > div.content > div:nth-child(6) > div.section_body > div.table_box > table > tbody > tr",
        "init_article_idx": 0,
        "css_title": "td.tal > a",
        "css_date": "td:nth-child(3)",
        "init_page_idx": 0,
        "css_pages": "#body > div.container > div.content > div:nth-child(6) > div.section_body > div.pagenate > span",
        "inner_href": {
            "css_href": "td.tal > a",
            "url_src": """f"https://www.smb-service.kr/pblanc/readUser/{btn_href.get_attribute("href").split("'")[1]}?page=5" """,
        },
    },
    "중소벤처기업부": {
        "url": "https://www.mss.go.kr/site/smba/ex/bbs/List.do?cbIdx=310#",
        "css_articles": "#contents_inner > div > table > tbody > tr",
        "init_article_idx": 0,
        "css_title": "td.subject > a",
        "css_date": "td:nth-child(7)",
        "init_page_idx": -1,
        "css_pages": "#contents_inner > div > div.paging > ul > li > a",
        "inner_href": {
            "css_href": "td.subject > a",
            "url_src": '''f"https://www.mss.go.kr/site/smba/ex/bbs/View.do?cbIdx=310&bcIdx={btn_href.get_attribute("onclick").split(',')[1][1:-1]}&parentSeq={btn_href.get_attribute("onclick").split(',')[1][1:-1]}"''',
        },
    },
    "중소벤처기업진흥공단": {
        "url": "http://www.kosmes.or.kr/sbc/SH/NTS/SHNTS001M0.do",
        "css_articles": "#AXGridTarget > tr",
        "init_article_idx": 0,
        "css_title": "td.bbs_tit > a",
        "css_date": "td:nth-child(4)",
        "init_page_idx": 0,
        "css_pages": "#pageApi > a",
        "inner_href": {
            "css_href": "td.bbs_tit > a",
            "url_src": '''f"http://www.kosmes.or.kr/sbc/SH/NTS/SHNTS001F0.do?seqNo={btn_href.get_attribute("onclick").split('(')[1].split(')')[0]}&nowPage=PAGEIDX&searchG=titleCon&searchT="''',
        },
    },
    "한국데이터산업진흥원": {
        "url": "https://www.kdata.or.kr/kr/board/notice_01/boardList.do",
        "css_articles": "#cont_wrap > div > ul > li",
        "init_article_idx": 1,
        "css_title": "p.tit > a",
        "css_date": "p.date > span:nth-child(2)",
        "init_page_idx": 1,
        "css_pages": "#cont_wrap > div > p.pagination > a",
        "inner_href": {
            "css_href": None,
            "url_src": """f"https://www.kdata.or.kr/kr/board/notice_01/boardView.do?pageIndex={page}&bbsIdx={btn_href.get_attribute("onclick").split("'")[1]}&searchCondition=all&searchKeyword=" """,
        },
    },
    "한국데이터산업협회": {
        "url": "http://www.kodia.kr/bbs/notice",
        "css_articles": "body > div.article > div > div.table-responsive.w-100 > table > tbody > tr",
        "init_article_idx": 0,
        "css_title": "td.text-left > a",
        "css_date": "td:nth-child(5)",
        "init_page_idx": 0,
        "css_pages": "body > div.article > div > div.text-center.mt-5 > a",
        "inner_href": {
            "css_href": "td.text-left > a",
            "url_src": """f"{btn_href.get_attribute("href")}" """,
        },
    },
    "한국산업기술진흥협회": {
        "url": "https://www.koita.or.kr/board/commBoardNotice003List.do",
        "css_articles": "#contents > article > div > div > div > div.cnt_s > div.x_tb_w > table > tbody > tr",
        "init_article_idx": 0,
        "css_title": "td:nth-child(2) > a",
        "css_date": "td.td_date",
        "init_page_idx": 0,
        "css_pages": "#paging > ol > li > a",
        "inner_href": {
            "css_href": "td:nth-child(2) > a",
            "url_src": """f"https://www.koita.or.kr/board/{btn_href.get_attribute("href").split("'")[1]}.do?page={page}&no={btn_href.get_attribute("href").split(" ")[5]}" """,
        },
    },
    "한국산업지능화협회": {
        "url": "https://www.koiia.or.kr/board/list.php?M2_IDX=21989",
        "css_articles": "#board-outer > div > div > div > div.koiia-wrap-list > table > tbody > tr",
        "init_article_idx": 0,
        "css_title": "td.link > a",
        "css_date": "td:nth-child(3)",
        "init_page_idx": 1,
        "css_pages": "#board-outer > div > div > div > div.koiia-wrap-list > div > a",
        "inner_href": {
            "css_href": "td.link > a",
            "url_src": """btn_href.get_attribute("href")""",
        },
    },
    "한국소프트웨어산업협회": {
        "url": "https://www.sw.or.kr/site/sw/ex/board/List.do?cbIdx=290",
        "css_articles": "#BbsContentFVo > div.board > div.board > table > tbody > tr",
        "init_article_idx": 0,
        "css_title": "td.left > a",
        "css_date": "td:nth-child(4)",
        "init_page_idx": 2,
        "css_pages": "#BbsContentFVo > div.board > ul > li > a",
        "inner_href": {
            "css_href": "td.left > a",
            "url_src": """f\'\'\'https://www.sw.or.kr/{btn_href.get_attribute("onclick")}\'\'\'""",
        },
    },
    "한국정보산업연합회": {
        "url": "https://www.fkii.org/bbs/board.php?tbl=itnews&&chr=&category=&findType=&findWord=&sort1=&sort2=",
        "css_articles": "#test > div > table > tbody > tr",
        "init_article_idx": 0,
        "css_title": "td.subject > a",
        "css_date": "td:nth-child(3)",
        "init_page_idx": -1,
        "css_pages": "#Board > div.pageArea > a",
        "inner_href": {
            "css_href": "td.subject > a",
            "url_src": """f"{btn_href.get_attribute("href")}" """,
        },
    },
    "한국지능정보사회진흥원": {
        "url": "https://www.nia.or.kr/site/nia_kor/ex/bbs/List.do?cbIdx=78336",
        "css_articles": "#sub_contentsArea > div.board_type01 > ul > li",
        "init_article_idx": 0,
        "css_title": "a > span.subject.searchItem",
        "css_date": "a > span.src > em:nth-child(1)",
        "init_page_idx": 2,
        "css_pages": "#sub_contentsArea > div.pageNation > span > a",
        "inner_href": {
            "css_href": "a",
            "url_src": """f"https://www.nia.or.kr/site/nia_kor/ex/bbs/View.do?cbIdx={btn_href.get_attribute("onclick").replace("'", "").split("(")[1].split(",")[:2][0]}&bcIdx={btn_href.get_attribute("onclick").replace("'", "").split("(")[1].split(",")[:2][1]}&parentSeq={btn_href.get_attribute("onclick").replace("'", "").split("(")[1].split(",")[:2][1]}" """,
        },
    },
    "한국클라우드산업협회": {
        "url": "https://kcloud.or.kr/board/list.php?M2_IDX=25869",
        "css_articles": "#board-outer > div > div > div > div.mboard-list-area > div.mboard-list > table > tbody > tr",
        "init_article_idx": 0,
        "css_title": "td.tit > a",
        "css_date": "td.date",
        "init_page_idx": 0,
        "css_pages": "#board-outer > div > div > div > div.mboard-list-area > div.pagenate > div > a",
        "inner_href": {
            "css_href": None,
            "url_src": """f\'\'\'https://kcloud.or.kr/board/read.php?M2_IDX=25869&BCL_IDX=1447&PAGE=1&B_IDX=61265{btn_href.get_attribute("onclick").split("'")[1]}\'\'\'""",
        },
    },
    "중소기업 혁신바우처 플랫폼": {
        "url": """https://www.mssmiv.com/portal/board/BoardList""",
        "css_articles": "#contents > div > div > form > div.tableList.mT35 > table > tbody > tr",
        "init_article_idx": 0,
        "css_title": """td.text-left > div > a""",
        "css_date": """td:nth-child(3)""",
        "init_page_idx": 0,
        "css_pages": """#contents > div > div > form > div.paging.mT30 > a""",
        "inner_href": {
            "css_href": "td.text-left > div > a",
            "url_src": """f"https://www.mssmiv.com/portal/board/BoardList" """,
        },
    },
}
